"""add backtest signal samples

Revision ID: 035961ea1c25
Revises: 86245d38f48d
Create Date: 2026-09-16 10:42:17.912880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '035961ea1c25'
down_revision: Union[str, None] = '86245d38f48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_signal_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('signal_contributions', sa.JSON(), nullable=False),
    sa.Column('actual_direction', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of_date', name='uq_backtest_sample')
    )
    op.create_index(op.f('ix_backtest_signal_samples_as_of_date'), 'backtest_signal_samples', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_backtest_signal_samples_instrument_id'), 'backtest_signal_samples', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_signal_samples_instrument_id'), table_name='backtest_signal_samples')
    op.drop_index(op.f('ix_backtest_signal_samples_as_of_date'), table_name='backtest_signal_samples')
    op.drop_table('backtest_signal_samples')
    # ### end Alembic commands ###
