"""add ai trading account kind, order reason, valuation snapshots

Revision ID: 457173dbb98f
Revises: 88d3a8f372c0
Create Date: 2026-09-15 17:14:58.446634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '457173dbb98f'
down_revision: Union[str, None] = '88d3a8f372c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_valuation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_jpy', sa.Float(), nullable=False),
    sa.Column('holdings_value_jpy', sa.Float(), nullable=False),
    sa.Column('total_value_jpy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_valuation_snapshots_account_id'), 'paper_valuation_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_valuation_snapshots_ts'), 'paper_valuation_snapshots', ['ts'], unique=False)
    # server_default backfills the existing manual paper account row; the
    # ORM-level default ("manual") keeps handling new rows afterwards.
    op.add_column(
        'paper_account',
        sa.Column('kind', sa.String(length=16), nullable=False, server_default='manual'),
    )
    op.alter_column('paper_account', 'kind', server_default=None)
    op.create_unique_constraint('uq_paper_account_kind', 'paper_account', ['kind'])
    op.add_column('paper_orders', sa.Column('prediction_id', sa.Integer(), nullable=True))
    op.add_column('paper_orders', sa.Column('reason', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_paper_orders_prediction_id', 'paper_orders', 'predictions', ['prediction_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_paper_orders_prediction_id', 'paper_orders', type_='foreignkey')
    op.drop_column('paper_orders', 'reason')
    op.drop_column('paper_orders', 'prediction_id')
    op.drop_constraint('uq_paper_account_kind', 'paper_account', type_='unique')
    op.drop_column('paper_account', 'kind')
    op.drop_index(op.f('ix_paper_valuation_snapshots_ts'), table_name='paper_valuation_snapshots')
    op.drop_index(op.f('ix_paper_valuation_snapshots_account_id'), table_name='paper_valuation_snapshots')
    op.drop_table('paper_valuation_snapshots')
    # ### end Alembic commands ###
