"""add strategy signal weights and prediction signal_contributions

Revision ID: 86245d38f48d
Revises: 457173dbb98f
Create Date: 2026-09-16 09:20:31.607077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86245d38f48d'
down_revision: Union[str, None] = '457173dbb98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_signal_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_name', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_name', name='uq_strategy_signal_name')
    )
    # server_default backfills existing prediction rows made before this
    # column existed; the ORM-level default (dict) handles new rows.
    op.add_column(
        'predictions',
        sa.Column('signal_contributions', sa.JSON(), nullable=False, server_default='{}'),
    )
    op.alter_column('predictions', 'signal_contributions', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'signal_contributions')
    op.drop_table('strategy_signal_weights')
    # ### end Alembic commands ###
