"""widen news url to text

Revision ID: 88d3a8f372c0
Revises: 96d40f568c78
Create Date: 2026-09-15 16:38:17.222584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88d3a8f372c0'
down_revision: Union[str, None] = '96d40f568c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_articles', 'url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_articles', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
